# Generated by Django 3.2.25 on 2024-05-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20240523_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
