# Generated by Django 3.2.25 on 2024-05-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('url', models.URLField()),
                ('http_method', models.CharField(max_length=255)),
                ('headers', models.JSONField()),
            ],
        ),
        migrations.RenameField(
            model_name='account',
            old_name='account_id',
            new_name='accountID',
        ),
        migrations.AlterField(
            model_name='account',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
